Hw04 auth
MateuszCharysz/nodejs-hw-templ pull request #3
Opened 2023-08-31 21:15 UTC by MateuszCharysz

bez zadania dodatkowego.
Ścieżki dla usera powinny działać. token ustawiony na godzinę:
Istniejący user:
`{
  "email": "example@example.com",
  "password": "examplepassword"
}`
Przypisany jest do niego 1 kontakt

2023-09-01 09:35 UTC, RadziuMM requested changes
Mógł byś jeszcze nazwy folderów ogranąć 00midelwares i 01routes (usuń numerację)

2023-09-01 09:35 UTC, RadziuMM commented on 00middleweres/jwtStrategy.js
> +    if (!user || err) {
tu trzeba jeszcze sprawdzić czy user.token jest taki sam jak token z req (tam trzeba przy porównaniu odjąć przedrostek bearer). Teraz mogę się wylogować a stary token np przy /current zadziała

2023-09-02 00:31 UTC, RadziuMM approved these changes

2023-09-02 00:31 UTC, RadziuMM commented on middleweres/jwtStrategy.js
> +const auth = async (req, res, next) => {
O takie coś mi chodziło, weź tu zmień na to a ja już zaliczam
```
const auth = (req, res, next) => {
	const token = req.headers.authorization?.split(" ")[1];
	passport.authenticate("jwt", { session: false }, (err, user) => {
		if (err || !user || !user.token || user.token !== token) {
			return res.status(401).json({
				status: "fail",
				code: 401,
				message: "Not authorized",
			});
		}
		req.user = user;
		next();
	})(req, res, next);
};
```

2023-09-02 11:42 UTC, MateuszCharysz commented
dzięki.. widze już gdzie był błąd.. wcześniej sprawdzałem tylko id co było bez sensu.. sprawdzenie tokena nie mogłoby się odbyć w strategii bo nie ma tam "przychodzącego" tokena

2023-09-02 11:42 UTC, merged